services:
  - type: web
    name: deepguardian-website
    env: prod
    region: oregon
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: WEB_SERVER_PORT
        value: "5000"
      - key: API_BASE_URL
        fromGroup: deepguardian-env
        type: secret
      - key: DEEPFAKE_API_ENDPOINT
        value: "/api/video/"
      - key: AUDIO_API_ENDPOINT
        value: "/api/audio/"
      - key: IMAGE_API_ENDPOINT
        value: "/api/image/"
      - key: MISINFORMATION_API_ENDPOINT
        value: "/api/text/"